<div style="font-weight:500;font-size:50px;text-align:center;">Numpy</div>





<div style="font-weight: 900;font-size:20px;margin:20px 10px;">Run this Buddy!!! <br>👇🏻👇🏻👇🏻👇🏻 </div>



In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9])


print(arr)
type(arr)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray


<div style="font-size:20px;">To check Numpy version </div>


In [4]:
np.__version__

'1.22.4'


<div style="font-size:20px;">Dimension in Arrays </div>



In [16]:
# 0D Array
arr = np.array(42)
print(arr)

# 1D Array
arr = np.array([1,2,3,4,5,6,7])
print(arr)


# 2D Array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


# 3D Array
arr = np.array([[[1,2],[3,4],[5,6,7]]])
print(arr)

# Higher Dimension Array
arr = np.array([1,2,3,4,5,6,7] , ndmin=5)
print(arr)


42
[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]]
[[list([1, 2]) list([3, 4]) list([5, 6, 7])]]
[[[[[1 2 3 4 5 6 7]]]]]


C:\Users\goyam\AppData\Local\Temp\ipykernel_12972\3642536584.py:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[[1,2],[3,4],[5,6,7]]])



                
<div style="font-size:20px;">Slicing Arrays: <br>
                We pass slice instead of index like this : [start:end] or [start:end:step]

 </div>


In [26]:
arr = np.array([1,2,3,10,5,6,7])
print(arr[1:4])
print(arr[1:-2])
print(arr[1:5:2])
print(arr[::2])

[ 2  3 10]
[ 2  3 10  5]
[ 2 10]
[1 3 5 7]





                
<div style="font-size:15px;">Data Types in Numpy <br>
<br>
i - integer<br>
b - boolean<br>
u - unsigned integer<br>
f - float<br>
c - complex float<br>
m - timedelta<br>
M - datetime<br>
O - object<br>
S - string<br>
U - unicode string<br>
V - fixed chunk of memory for other type ( void )
 </div>



In [31]:

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

print()
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

print()
# 👇🏻👇🏻 It just throw an error bz the type is 'integer' and the data in there is string and integer
# arr = np.array(['a', '2', '3'], dtype='i')

[b'1' b'2' b'3' b'4']
|S1

[1 2 3 4]
int32



In [35]:
# Converting the arr after the data put in the array
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


print()
# Change data type from integer to boolean:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)


[1 2 3]
int32

[ True False  True]
bool


In [3]:
# you can use copy() function in numpy for make a copy of an array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
x= arr.copy()

x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# view function for just viewing the array but yout can change the data 👇🏻👇🏻👇🏻

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)
# 👇🏻👇🏻👇🏻

[42  2  3  4  5]
[42  2  3  4  5]


In [5]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


"Base " in view gives the array <br>
"Base" in copy gives None means that the array has having the values

In [12]:
arr = np.array([[1, 2, 3, 4, 5]])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[[1 2 3 4 5]]


shape checks the shape of the arrya data which dimension are they

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


Reshape the array from 1-D to 2-D <br> <br> 
you can't change in any shape for eg.  
We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# returning view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [25]:

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [26]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [28]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [30]:
#  first1 method for creating filter array
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [31]:
#  Second method for creating filter array it is short and sweet and fast making
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


<div style="font-weight:500;font-size:30px;text-align:center;">You have completed the Basics of Numpy Buddy👌👌<br><br> <span style="font-size:30px">Now Check this out 👇🏻👇🏻</span>  </div>


<div style="font-weight:500;font-size:50px;text-align:center;">Numpy Random</div>


In [47]:
from numpy import random

x = random.randint(100,size=(5))
x = random.randint(100, size=(3, 5))
x= random.choice([3,5,7,9],size=(3, 5))
print(x)

[[9 5 3 9 7]
 [5 3 3 7 3]
 [3 3 9 5 3]]


Shufffing Arrays in itself

if will generate random list of arrays from given array data <br> it also changes the main array<br>The shuffle() method makes changes to the original array.

In [9]:
from numpy import random


arr = np.array([1, 2, 3, 4, 5])


random.shuffle(arr)

print(arr)

[4 1 3 2 5]


$Permutation$ $ Arrays$

Permuntation arrays don't change the orginal array as shuffle() method do...

In [10]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[4 5 2 1 3]
